name: Android CI Buildozer Automatic

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          # Installiamo le dipendenze essenziali per Kivy e Buildozer
          sudo apt install -y build-essential git zip unzip libtool m4 \
                              openjdk-17-jdk curl autoconf automake \
                              zlib1g-dev libjpeg-dev libpng-dev \
                              libfreetype6-dev libsdl2-dev libsdl2-image-dev \
                              libsdl2-mixer-dev libsdl2-ttf-dev \
                              libportmidi-dev libswscale-dev libavformat-dev \
                              libavcodec-dev
          
          # Aggiorniamo pip e installiamo buildozer e cython
          pip install --upgrade pip
          pip install buildozer cython

      - name: Setup Java Home
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Compile APK via Buildozer (Release Finale)
        if: success()
        env:
          JAVA_HOME: ${{ env.JAVA8_HOME }}
          ANDROID_API: 28 
          ANDROID_NDK: /home/runner/.buildozer/android/platform/android-ndk-r25c
          NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk-r25c
          P4A_COMPILE_ENDIAN_SINGLE: 1 
          ANDROID_SDK_IGNORE_LICENSES: 1 
          # Sblocca la compilazione con org.test
          BUILDOZER_ALLOW_ORG_TEST_DOMAIN: 1 
        run: |
          buildozer android release

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk-release
          path: bin/*.apk
